### ISSUE TITLE
Reputation bars not changing when entering new zones

### ISSUE THREAD

**Issue by Nabohs** [Myrroddin/repbyzone#4]
Selected Honor Hold and went to both Zangarmarsh and Terrokar Forest and it wouldn't change. No issue being detected on Swatter

**Comment by Nabohs** [comment]
Pulled from Swatter

Date: 2021-06-05 14:17:48
ID: 6
Error occured in: Global
Count: 1
Message: ..\AddOns\RepByZone\Options.lua line 44:
   Usage: RegisterEvent("eventname", "methodname"): 'methodname' - method 'ZONE_CHANGED' not found on self.
Debug:
   [string "=[C]"]: ?
   [string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:112: RegisterEvent()
   [string "@RepByZone\Options.lua"]:44:
      RepByZone\Options.lua:41
   [string "=[C]"]: ?
   [string "@Atlas\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:51:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49
   [string "@Atlas\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:847:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:668
   [string "=[C]"]: ?
   [string "@Atlas\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:72:
      ...nterface\AddOns\Atlas\Libs\AceGUI-3.0\AceGUI-3.0.lua:70
   [string "@Atlas\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:306: Fire()
   [string "@Atlas\Libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua"]:68:
      ...as\Libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57
Locals:
None
AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  AdiBags, vv1.9.24-bcc
  AdvancedInterfaceOptions, v1.5.0-1-gcd568fb
  Atlas, vv1.49.00
  AtlasBurningCrusade, vv1.49.00
  AtlasClassicWoW, vv1.49.00
  AtlasLootClassic, vv2.3.0-bcc
  AtlasLootClassicData, vv2.3.0-bcc
  AtlasLootClassicDungeonsAndRaids, vv2.3.0-bcc
  Attune, v227
  AucAdvanced, v1.13.6707 (SwimmingSeadragon)
  AucFilterBasic, v1.13.6680 (SwimmingSeadragon)
  AucScanData, v1.13.6630 (SwimmingSeadragon)
  AucStatHistogram, v1.13.6681 (SwimmingSeadragon)
  AucStatiLevel, v1.13.6705 (SwimmingSeadragon)
  AucStatPurchased, v1.13.6672 (SwimmingSeadragon)
  AucStatSimple, v1.13.6634 (SwimmingSeadragon)
  AucStatStdDev, v1.13.6635 (SwimmingSeadragon)
  AucUtilFixAH, v1.13.6608 (SwimmingSeadragon)
  Auctionator, v100.0.11
  Aurora, v9.0.5.0
  AutoCarrot, v1.13.12
  AutoVendor, v68-classic
  BeanCounter, v1.13.6682 (SwimmingSeadragon)
  BlizzMove, vv3.0.19
  ClassicAuraDurations, v2.5.4
  ClassicCastbars, vv1.4.0
  ClassicCastbarsOptions, vv1.4.0
  DBMAceAttorneyMusicPack, v1.0.0
  DBMCore, v2.5.4
  DBMPartyBC, v2.5.4
  DBMStatusBarTimers, v
  DBMVPHazelNutty, v1.1
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Dominos, v9.0.28
  DominosCast, v
  DominosConfig, v
  DominosEncounter, v
  DominosProgress, v
  DominosRoll, v
  ElkBuffBars, v2.6.2-199
  Enchantrix, v1.13.6662 (SwimmingSeadragon)
  EnchantrixBarker, v1.13.6692 (SwimmingSeadragon)
  Gnosis, vr241
  Immersion, v1.3.7
  Informant, v1.13.6684 (SwimmingSeadragon)
  ItemRack, v
  ItemTooltipProfessionIcons, v1.2
  KuiMedia, v
  KuiNameplates, v2.27.3a
  KuiNameplatesCore, v
  LeatrixMaps, v2.5.38
  LeatrixPlus, v2.5.38
  Masque, v9.0.6
  MasqueSerenity, v9.0.7
  MaxCam, v2.5.1
  MBB, v1.2.0
  MikScrollingBattleText, v5.7.152
  NovaInstanceTracker, v1.17
  NovaWorldBuffs, v2.08
  OmniCC, v9.0.10
  Postal, vr436
  Prat30, v3.9.1
  Prat30Libraries, v
  Questie, v6.3.14
  RepByZone, v1.19.5
  SexyMap, vv3-bcc
  ShadowedUnitFrames, vv4.3.1-classic-1-gf597a16
  SheepMonitor, v1.23
  SinStats, v3.2.1
  SpellbookAbridged, v2.6.4a
  Stubby, v1.13.6614 (SwimmingSeadragon)
  TipTac, v21.05.26
  TipTacItemRef, v21.05.11
  TranqRotate, v1.7.0
  WeakAuras, v3.4.2
  WeakAurasCompanion, v1.1.0
  WeakAurasOptions, v3.4.2
  WeaponSwingTimer, v6.3.4
  WowUp, v1.0.0
  wowupdataaddon, v1.0.0
  BlizRuntimeLib_enUS v2.5.1.20501 <none>
  (ck=943)

**Comment by Myrroddin** [comment]
I had an extra line in both classic and BCC, which will get removed for 1.19.6, whenever GitHub processes that version.

**Comment by Myrroddin** [comment]
Fixed with RBZ 1.19.6
