### ISSUE TITLE
[Issue] RBZ not listed in the addon list nor working ingame

### ISSUE THREAD

**Issue by antarek** [Myrroddin/repbyzone#6]
RBZ version: 1.21.13
Game version: 10.0.2.47213
Client language: French

Hi, as the title says RBZ isn't lised among my addons list using the default Blizzard addon interface (it is listed among my installed addons list from the Addon Control Panel addon tho which is weird). Using the /rbz (or any others) command ingame does nothing.

**Comment by Myrroddin** [comment]
I never check GitHub for issues, which is why I didn't notice this until now. In the future, please use https://www.curseforge.com/wow/addons/repbyzone/issues if anything comes up.
